export default {
  "0e384e19": [() => import(/* webpackChunkName: "0e384e19" */ "@site/docs/intro.md"), "@site/docs/intro.md", require.resolveWeak("@site/docs/intro.md")],
  "17896441": [() => import(/* webpackChunkName: "17896441" */ "@theme/DocItem"), "@theme/DocItem", require.resolveWeak("@theme/DocItem")],
  "5e95c892": [() => import(/* webpackChunkName: "5e95c892" */ "@theme/DocsRoot"), "@theme/DocsRoot", require.resolveWeak("@theme/DocsRoot")],
  "935f2afb": [() => import(/* webpackChunkName: "935f2afb" */ "~docs/default/version-current-metadata-prop-751.json"), "~docs/default/version-current-metadata-prop-751.json", require.resolveWeak("~docs/default/version-current-metadata-prop-751.json")],
  "95c96e12": [() => import(/* webpackChunkName: "95c96e12" */ "@site/docs/instructor/technical-guide.md"), "@site/docs/instructor/technical-guide.md", require.resolveWeak("@site/docs/instructor/technical-guide.md")],
  "a7bd4aaa": [() => import(/* webpackChunkName: "a7bd4aaa" */ "@theme/DocVersionRoot"), "@theme/DocVersionRoot", require.resolveWeak("@theme/DocVersionRoot")],
  "a94703ab": [() => import(/* webpackChunkName: "a94703ab" */ "@theme/DocRoot"), "@theme/DocRoot", require.resolveWeak("@theme/DocRoot")],
  "b84714c6": [() => import(/* webpackChunkName: "b84714c6" */ "/Users/hansghezzi/Desktop/Hans Personal/PersonalProjects/Sequencing_Monopoly_game/microbiopoly/website/.docusaurus/docusaurus-plugin-content-docs/default/plugin-route-context-module-100.json"), "/Users/hansghezzi/Desktop/Hans Personal/PersonalProjects/Sequencing_Monopoly_game/microbiopoly/website/.docusaurus/docusaurus-plugin-content-docs/default/plugin-route-context-module-100.json", require.resolveWeak("/Users/hansghezzi/Desktop/Hans Personal/PersonalProjects/Sequencing_Monopoly_game/microbiopoly/website/.docusaurus/docusaurus-plugin-content-docs/default/plugin-route-context-module-100.json")],
  "c290ad13": [() => import(/* webpackChunkName: "c290ad13" */ "@site/docs/student-guide.md"), "@site/docs/student-guide.md", require.resolveWeak("@site/docs/student-guide.md")],
  "f2d0d075": [() => import(/* webpackChunkName: "f2d0d075" */ "@site/docs/instructor/pedagogy.md"), "@site/docs/instructor/pedagogy.md", require.resolveWeak("@site/docs/instructor/pedagogy.md")],};
